merge in custom RR datadog changes

diff --git a/ecs-deploy b/ecs-deploy
--- a/ecs-deploy
+++ b/ecs-deploy
@@ -1,5 +1,11 @@
 #!/usr/bin/env bash
 
+#############################################################################
+# Fork of https://github.com/silinternational/ecs-deploy
+# License: MIT see https://github.com/silinternational/ecs-deploy/blob/b186db2820fdc249b97da40994ca4e26771446bc/LICENSE
+# Modified to update environment variables DD_VERSION in task definitions with new argument `--datadog-version`
+#############################################################################
+
 # Setup default values for variables
 VERSION="3.10.8"
 CLUSTER=false
@@ -28,6 +34,7 @@ RUN_TASK_NETWORK_CONFIGURATION=false
 RUN_TASK_WAIT_FOR_SUCCESS=false
 TASK_DEFINITION_TAGS=false
 COPY_TASK_DEFINITION_TAGS=false
+DD_VERSION=""
 
 function usage() {
     cat <<EOM
@@ -370,12 +377,17 @@ function createNewTaskDefJson() {
             | jq '.taskDefinition' )
     fi
 
+    #Update TASK defintion DD_VERSION env var
+    DEF=$( echo "$DEF" | jq --arg dd_version "$DD_VERSION" '(.containerDefinitions[].environment[] | select (.name == "DD_VERSION")).value |= $dd_version' )
+    DEF=$( echo "$DEF" | jq --arg dd_version "$DD_VERSION" '(.containerDefinitions[].environment[] | select (.name == "RR_APP_VERSION")).value |= $dd_version' )
+    DEF=$( echo "$DEF" | jq --arg dd_version "$DD_VERSION" '(.containerDefinitions[].dockerLabels."com.datadoghq.tags.version") |= $dd_version' )
+
     # Default JQ filter for new task definition
     NEW_DEF_JQ_FILTER="family: .family, volumes: .volumes, containerDefinitions: .containerDefinitions, placementConstraints: .placementConstraints"
 
     # Some options in task definition should only be included in new definition if present in
     # current definition. If found in current definition, append to JQ filter.
-    CONDITIONAL_OPTIONS=(networkMode taskRoleArn placementConstraints executionRoleArn runtimePlatform)
+    CONDITIONAL_OPTIONS=(networkMode taskRoleArn placementConstraints executionRoleArn)
     for i in "${CONDITIONAL_OPTIONS[@]}"; do
       re=".*${i}.*"
       if [[ "$DEF" =~ $re ]]; then
@@ -405,7 +417,7 @@ function createNewTaskDefJson() {
 
 function registerNewTaskDefinition() {
     # Register the new task definition, and store its ARN
-    if [[ "$COPY_TASK_DEFINITION_TAGS" == true && "$TASK_DEFINITION_TAGS" != false && "$TASK_DEFINITION_TAGS" != "[]" ]]; then
+    if [[ "$COPY_TASK_DEFINITION_TAGS" == true && "$TASK_DEFINITION_TAGS" != false ]]; then
       NEW_TASKDEF=`$AWS_ECS register-task-definition --cli-input-json "$NEW_DEF" --tags "$TASK_DEFINITION_TAGS" | jq -r .taskDefinition.taskDefinitionArn`
     else
       NEW_TASKDEF=`$AWS_ECS register-task-definition --cli-input-json "$NEW_DEF" | jq -r .taskDefinition.taskDefinitionArn`
@@ -454,36 +466,59 @@ function updateService() {
     # Only excepts RUNNING state from services whose desired-count > 0
     SERVICE_DESIREDCOUNT=`$AWS_ECS describe-services --cluster $CLUSTER --service $SERVICE | jq '.services[]|.desiredCount'`
     if [ $SERVICE_DESIREDCOUNT -gt 0 ]; then
-      if [[ $MAX_DEFINITIONS -gt 0 ]]; then
-          FAMILY_PREFIX=${TASK_DEFINITION_ARN##*:task-definition/}
-          FAMILY_PREFIX=${FAMILY_PREFIX%*:[0-9]*}
-          TASK_REVISIONS=`$AWS_ECS list-task-definitions --family-prefix $FAMILY_PREFIX --status ACTIVE --sort ASC`
-          NUM_ACTIVE_REVISIONS=$(echo "$TASK_REVISIONS" | jq ".taskDefinitionArns|length")
-          if [[ $NUM_ACTIVE_REVISIONS -gt $MAX_DEFINITIONS ]]; then
-              LAST_OUTDATED_INDEX=$(($NUM_ACTIVE_REVISIONS - $MAX_DEFINITIONS - 1))
-              for i in $(seq 0 $LAST_OUTDATED_INDEX); do
-                  OUTDATED_REVISION_ARN=$(echo "$TASK_REVISIONS" | jq -r ".taskDefinitionArns[$i]")
+        # See if the service is able to come up again
+        every=10
+        i=0
+        while [ $i -lt $TIMEOUT ]
+        do
+            # Scan the list of running tasks for that service, and see if one of them is the
+            # new version of the task definition
 
-                  echo "Deregistering outdated task revision: $OUTDATED_REVISION_ARN"
+            RUNNING_TASKS=$($AWS_ECS list-tasks --cluster "$CLUSTER"  --service-name "$SERVICE" --desired-status RUNNING \
+                | jq -r '.taskArns[]')
 
-                $AWS_ECS deregister-task-definition --task-definition "$OUTDATED_REVISION_ARN" > /dev/null
-              done
-          fi
+            if [[ ! -z $RUNNING_TASKS ]] ; then
+                RUNNING=$($AWS_ECS describe-tasks --cluster "$CLUSTER" --tasks $RUNNING_TASKS \
+                    | jq ".tasks[]| if .taskDefinitionArn == \"$NEW_TASKDEF\" then . else empty end|.${checkFieldName}" \
+                    | grep -e "${checkFieldValue}") || :
 
-          fi
-          UPDATE_SERVICE_SUCCESS="true"
-          break
+                if [ "$RUNNING" ]; then
+                    echo "Service updated successfully, new task definition running.";
+
+                    if [[ $MAX_DEFINITIONS -gt 0 ]]; then
+                        FAMILY_PREFIX=${TASK_DEFINITION_ARN##*:task-definition/}
+                        FAMILY_PREFIX=${FAMILY_PREFIX%*:[0-9]*}
+                        TASK_REVISIONS=`$AWS_ECS list-task-definitions --family-prefix $FAMILY_PREFIX --status ACTIVE --sort ASC`
+                        NUM_ACTIVE_REVISIONS=$(echo "$TASK_REVISIONS" | jq ".taskDefinitionArns|length")
+                        if [[ $NUM_ACTIVE_REVISIONS -gt $MAX_DEFINITIONS ]]; then
+                            LAST_OUTDATED_INDEX=$(($NUM_ACTIVE_REVISIONS - $MAX_DEFINITIONS - 1))
+                            for i in $(seq 0 $LAST_OUTDATED_INDEX); do
+                                OUTDATED_REVISION_ARN=$(echo "$TASK_REVISIONS" | jq -r ".taskDefinitionArns[$i]")
+
+                                echo "Deregistering outdated task revision: $OUTDATED_REVISION_ARN"
+
+                              $AWS_ECS deregister-task-definition --task-definition "$OUTDATED_REVISION_ARN" > /dev/null
+                            done
+                        fi
+
+                    fi
+                    UPDATE_SERVICE_SUCCESS="true"
+                    break
+                fi
+            fi
+
+            sleep $every
+            i=$(( $i + $every ))
+        done
+
+        if [[ "${UPDATE_SERVICE_SUCCESS}" != "true" ]]; then
+            # Timeout
+            echo "ERROR: New task definition not running within $TIMEOUT seconds"
+            if [[ "${ENABLE_ROLLBACK}" != "false" ]]; then
+              rollback
+            fi
+            exit 1
         fi
-      fi
-      
-      if [[ "${UPDATE_SERVICE_SUCCESS}" != "true" ]]; then
-          # Timeout
-          echo "ERROR: New task definition not running within $TIMEOUT seconds"
-          if [[ "${ENABLE_ROLLBACK}" != "false" ]]; then
-            rollback
-          fi
-          exit 1
-      fi
     else
         echo "Skipping check for running task definition, as desired-count <= 0"
     fi
@@ -496,24 +531,11 @@ function waitForGreenDeployment {
   echo "Waiting for service deployment to complete..."
   while [ $i -lt $TIMEOUT ]
   do
-    DEPLOYMENTS=$($AWS_ECS describe-services --services $SERVICE --cluster $CLUSTER)
-    NEW_DEPLOYMENT=$(echo $DEPLOYMENTS | jq ".services[].deployments[] | select(.taskDefinition == \"$NEW_TASKDEF\")")
-    DEPLOYMENTS_COUNT=$(echo $DEPLOYMENTS | jq ".services[].deployments | length")
-    
-    # if this is empty, it means the new (expected) deploy hasnt picked up yet
-    if [ -z "$NEW_DEPLOYMENT" ]; then
-      sleep $every
-      i=$(( $i + $every ))
-      continue
-    fi
-    
-    COUNT_DESIRED=$(echo $NEW_DEPLOYMENT | jq -r '.desiredCount')
-    COUNT_LAUNCHED=$(echo $NEW_DEPLOYMENT | jq -r '.runningCount')
+    NUM_DEPLOYMENTS=$($AWS_ECS describe-services --services $SERVICE --cluster $CLUSTER | jq "[.services[].deployments[]] | length")
 
-    # Compare counts of launched new containers vs. requested
-    # and continue when all new services are launched.
+    # Wait until 1 deployment stays running
     # If the wait time has passed, we need to roll back
-    if [ "$COUNT_DESIRED" == "$COUNT_LAUNCHED" ] && [ $DEPLOYMENTS_COUNT -eq 1 ]; then
+    if [ $NUM_DEPLOYMENTS -eq 1 ]; then
       echo "Service deployment successful."
       DEPLOYMENT_SUCCESS="true"
       # Exit the loop.
@@ -651,6 +673,10 @@ if [ "$BASH_SOURCE" == "$0" ]; then
                 ;;
             -i|--image)
                 IMAGE="$2"
+                shift
+                ;;
+            --datadog-version)
+                DD_VERSION="$2"
                 shift
                 ;;
             -t|--timeout)
